// miscellaneous shared variables, mostly nasty stuff

export let data = {
  testSuiteDimension: undefined,
  testResult: "RESERVEDTESTRESULTFLAG",
  testStatus: "RESERVEDTESTSTATUSARRAY",
  environment: "RESERVEDLOCALENVIRONMENTDICTIONARY",
  getOutput: "RESERVEDSTDOUTOUTPUTFUNCTION",
  globals: "RESERVEDGLOBALSARRAY",
  imports: "RESERVEDIMPORTNAMEARRAY",
  empty: "RESERVEDINSPECTEMPTY",
  signature: "RESERVEDINSPECTSIGNATURE",
  getfile: "RESERVEDINSPECTGETFILE",
  ismodule: "RESERVEDINSPECTISMODULE",
  getmodule: "RESERVEDINSPECTGETMODULE",
  name: "RESERVEDOBJECTNAMEITERATOR",
  obj: "RESERVEDOBJECTITERATOR",
  k: "RESERVEDKEYITERATOR",
  v: "RESERVEDVALUEITERATOR",
  p: "RESERVEDPARAMETERITERATOR",
  getframeinfo: "RESERVEDINSPECTGETFRAMEINFO",
  currentframe: "RESERVEDINSPECTCURRENTFRAME",
  extractTb: "RESERVEDTRACEBACKEXTRACTTB",
  i: "RESERVEDINDEXITERATORI",
  j: "RESERVEDINDEXITERATORJ",
  lineno: "RESERVEDLINENUMBER",
};
// TODO sync testSuiteDimension to current test suite selection